FROM node:20-alpine AS build

ARG APK_MIRROR_HOST=mirrors.aliyun.com
ARG NPM_REGISTRY=https://registry.npmmirror.com

WORKDIR /app

COPY code/web/package.json ./package.json
COPY code/web/package-lock.json ./package-lock.json

RUN sed -i "s|https\\?://dl-cdn.alpinelinux.org/alpine|https://${APK_MIRROR_HOST}/alpine|g" /etc/apk/repositories \
    && npm config set registry ${NPM_REGISTRY} \
    && npm ci

COPY code/web/ ./

RUN npm run build

FROM nginx:1.27-alpine

COPY code/web/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
