from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class InferenceRequest(BaseModel):
    request_id: str = Field(description="Unique request id generated by the caller.")
    source_type: Literal["image", "video", "stream", "edge-report"]
    source_uri: str = Field(description="Path, URL or device source identifier.")
    occurred_at: datetime
    device_code: str | None = None
    frame_uri: str | None = None
    inference_mode: Literal["yolo-knn", "yolo-only"] = "yolo-knn"
    yolo_model_key: str | None = None
    metadata: dict[str, object] = Field(default_factory=dict)


class BehaviorEventCandidate(BaseModel):
    device_code: str
    event_time: datetime
    behavior_type: str
    cow_count: int
    confidence: float
    zone_name: str | None = None
    notes: str | None = None


class InferenceResponse(BaseModel):
    request_id: str
    service: str
    model_name: str
    model_version: str
    inference_source: str
    processed_at: datetime
    behavior_events: list[BehaviorEventCandidate]
    raw_metadata: dict[str, object] = Field(default_factory=dict)


class YoloModelOption(BaseModel):
    key: str
    label: str
    path: str
    is_default: bool = False


class InferenceMetaResponse(BaseModel):
    service: str
    service_mode: str
    supported_sources: list[Literal["image", "video", "stream", "edge-report"]]
    available_inference_modes: list[Literal["yolo-knn", "yolo-only"]]
    default_inference_mode: Literal["yolo-knn", "yolo-only"]
    default_yolo_model_key: str | None = None
    default_yolo_confidence: float
    default_yolo_iou: float
    default_knn_confidence_threshold: float
    available_yolo_models: list[YoloModelOption]
    knn_model_loaded: bool
